-- ============================================================
-- Sample Seed Data for Development & Testing
-- Passwords are bcrypt hashes of 'password123'
-- ============================================================
USE fintech_db;

-- Sample Users
/*INSERT INTO users (cnic, full_name, password_hash, status) VALUES
('35202-1234567-1', 'Muhammad Ahmed Khan',   '$2a$10$N.zmdr9zkoa05OY9JAVWTub8Y.6e6nppxYuLanCpLwcMxYRY0U4mm', 'ACTIVE'),
('35202-7654321-2', 'Ayesha Siddiqui',       '$2a$10$N.zmdr9zkoa05OY9JAVWTub8Y.6e6nppxYuLanCpLwcMxYRY0U4mm', 'ACTIVE'),
('42301-9876543-3', 'Ali Hassan Malik',      '$2a$10$N.zmdr9zkoa05OY9JAVWTub8Y.6e6nppxYuLanCpLwcMxYRY0U4mm', 'ACTIVE'),
('31202-1111111-4', 'Fatima Zahra',          '$2a$10$N.zmdr9zkoa05OY9JAVWTub8Y.6e6nppxYuLanCpLwcMxYRY0U4mm', 'ACTIVE');

-- Sample Accounts (linked to users by position, adjust IDs as needed)
-- Note: In production, account numbers are auto-generated by AuthService
INSERT INTO accounts (user_id, account_number, balance, currency) VALUES
(1, 'PKF-00100001', 75000.00, 'PKR'),
(2, 'PKF-00100002', 32500.50, 'PKR'),
(3, 'PKF-00100003', 120000.00, 'PKR'),
(4, 'PKF-00100004', 15000.75, 'PKR');

-- Sample Transactions
INSERT INTO transactions (sender_account_id, recipient_account_id, amount, status, reference_number, description) VALUES
(1, 2, 5000.00, 'SUCCESS', 'TXN-20240101-A1B2C3D4', 'Transfer to Ayesha Siddiqui'),
(3, 1, 10000.00, 'SUCCESS', 'TXN-20240102-E5F6G7H8', 'Transfer to Muhammad Ahmed Khan'),
(2, 4, 2500.00, 'SUCCESS', 'TXN-20240103-I9J0K1L2', 'Transfer to Fatima Zahra'),
(1, 3, 8000.00, 'SUCCESS', 'TXN-20240104-M3N4O5P6', 'Transfer to Ali Hassan Malik');
*/