# Datasource - MySQL
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=${DB_USER:fintech}
quarkus.datasource.password=${DB_PASS:fintech123}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:mysql://localhost:3306/fintech_db?serverTimezone=UTC&useSSL=false}

# Hibernate ORM
quarkus.hibernate-orm.database.generation=validate
quarkus.hibernate-orm.log.sql=false

# JWT config
mp.jwt.verify.issuer=https://fintech.local
mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=privateKey.pem

# App
quarkus.http.port=8080
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization

# OTP settings
app.otp.expiry-minutes=5
app.otp.max-attempts=3
app.jwt.expiry-hours=24
